services:
    zigbee2mqtt:
        container_name: zigbee2mqtt
        restart: unless-stopped
        image: koenkk/zigbee2mqtt:latest
        volumes:
            - zigbee2mqtt-data:/app/data
            - /run/udev:/run/udev:ro
        ports:
            - 8084:8080
        environment:
            - TZ=Europe/Berlin
        group_add:
            - dialout
        user: 1000:1000

volumes:
  zigbee2mqtt-data:
    external: true
